// export const sample_foods = [
//   {
//     id: "1",
//     name: "Pizza Pepperoni",
//     cookTime: "10-20",
//     price: 10,
//     favorite: false,
//     origins: ["italy"],
//     stars: 4.5,
//     imageUrl: "food-1.jpg",
//     tags: ["FastFood", "Pizza", "Lunch"],
//   },
//   {
//     id: "2",
//     name: "Meatball",
//     price: 20,
//     cookTime: "20-30",
//     favorite: true,
//     origins: ["persia", "middle east", "china"],
//     stars: 5,
//     imageUrl: "food-2.jpg",
//     tags: ["SlowFood", "Lunch"],
//   },
//   {
//     id: "3",
//     name: "Hamburger",
//     price: 5,
//     cookTime: "10-15",
//     favorite: false,
//     origins: ["germany", "us"],
//     stars: 3.5,
//     imageUrl: "food-3.jpg",
//     tags: ["FastFood", "Hamburger"],
//   },
//   {
//     id: "4",
//     name: "Fried Potatoes",
//     price: 2,
//     cookTime: "15-20",
//     favorite: true,
//     origins: ["belgium", "france"],
//     stars: 3,
//     imageUrl: "food-4.jpg",
//     tags: ["FastFood", "Fry"],
//   },
//   {
//     id: "5",
//     name: "Chicken Soup",
//     price: 11,
//     cookTime: "40-50",
//     favorite: false,
//     origins: ["india", "asia"],
//     stars: 3.5,
//     imageUrl: "food-5.jpg",
//     tags: ["SlowFood", "Soup"],
//   },
//   {
//     id: "6",
//     name: "Vegetables Pizza",
//     price: 9,
//     cookTime: "40-50",
//     favorite: false,
//     origins: ["italy"],
//     stars: 4.0,
//     imageUrl: "food-6.jpg",
//     tags: ["FastFood", "Pizza", "Lunch"],
//   },
//   {
//     id: "7",
//     name: "Vanilla Cupcake",
//     price: 10,
//     cookTime: "5-10",
//     favorite: false,
//     origins: ["india", "germany", "us"],
//     stars: 4.5,
//     imageUrl: "food-16.jfif",
//     tags: ["Cupcake"],
//   },
//   {
//     id: "8",
//     name: "Hot Pink Cupcake",
//     price: 20,
//     cookTime: "5-10",
//     favorite: true,
//     origins: ["india", "germany", "us"],
//     stars: 4.5,
//     imageUrl: "food-17.jfif",
//     tags: ["Cupcake"],
//   },
//   {
//     id: "9",
//     name: "Chocolate Cupcake",
//     price: 10,
//     cookTime: "5-10",
//     favorite: false,
//     origins: ["india"],
//     stars: 4.3,
//     imageUrl: "food-18.jpg",
//     tags: ["Cupcake"],
//   },
// ];

// export const sample_tags = [
//   { name: "All", count: 6 },
//   { name: "FastFood", count: 4 },
//   { name: "Pizza", count: 2 },
//   { name: "Lunch", count: 3 },
//   { name: "SlowFood", count: 2 },
//   { name: "Hamburger", count: 1 },
//   { name: "Fry", count: 1 },
//   { name: "Soup", count: 1 },
//   { name: "Cupcake", count: 3 },
// ];

// export const sample_users = [
//   {
//     id: 1,
//     name: "John Doe",
//     email: "john@gmail.com",
//     password: "12345",
//     address: "Toronto On",
//     isAdmin: false,
//   },
//   {
//     id: 2,
//     name: "Jane Doe",
//     email: "jane@gmail.com",
//     password: "12345",
//     address: "Shanghai",
//     isAdmin: true,
//   },
// ];

export const sample_foods = [
  {
    id: "1",
    name: "Idli Sambar",
    price: 20,
    cookTime: "10-20",
    favorite: true,
    origins: ["india"],
    stars: 4.5,
    imageUrl: "food-1.webp",
    tags: ["Breakfast"],
  },
  {
    id: "2",
    name: "Benne Dosa",
    price: 50,
    cookTime: "20-30",
    favorite: true,
    origins: ["india"],
    stars: 5,
    imageUrl: "food-2.jpg",
    tags: ["Breakfast", "Lunch"],
  },
  {
    id: "3",
    name: "Pizza Pepperoni",
    price: 100,
    cookTime: "10-15",
    favorite: false,
    origins: ["germany", "us", "india", "italy"],
    stars: 4.5,
    imageUrl: "food-3.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "4",
    name: "Meatball",
    price: 20,
    cookTime: "20-30",
    favorite: true,
    origins: ["persia", "middle east", "china"],
    stars: 5,
    imageUrl: "food-4.jpg",
    tags: ["SlowFood", "Lunch"],
  },
  {
    id: "5",
    name: "Paneer Butter Masala",
    price: 50,
    cookTime: "15-20",
    favorite: true,
    origins: ["india", "asia"],
    stars: 5,
    imageUrl: "food-5.webp",
    tags: ["Curry", "Lunch"],
  },
  {
    id: "6",
    name: "HamBurger",
    price: 50,
    cookTime: "20-30",
    favorite: false,
    origins: ["india", "germany", "us"],
    stars: 3.5,
    imageUrl: "food-6.jpg",
    tags: ["FastFood", "HamBurger"],
  },
  {
    id: "7",
    name: "French Fries",
    price: 9,
    cookTime: "20-30",
    favorite: true,
    origins: ["india", "us", "asia"],
    stars: 5,
    imageUrl: "food-7.jpg",
    tags: ["FastFood", "Fry"],
  },
  {
    id: "8",
    name: "Vegetables Pizza",
    price: 9,
    cookTime: "40-50",
    favorite: true,
    origins: ["italy", "india"],
    stars: 4.6,
    imageUrl: "food-8.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "9",
    name: "Vegetable Curry",
    price: 30,
    cookTime: "25-30",
    favorite: false,
    origins: ["india"],
    stars: 4.2,
    imageUrl: "food-9.png",
    tags: ["Curry", "Lunch"],
  },
  {
    id: "10",
    name: "Kabab",
    price: 9,
    cookTime: "30-35",
    favorite: false,
    origins: ["india"],
    stars: 4.5,
    imageUrl: "food-10.png",
    tags: ["Chicken", "Lunch"],
  },
  {
    id: "11",
    name: "Chocolate Cake",
    price: 300,
    cookTime: "40-50",
    favorite: true,
    origins: ["india"],
    stars: 4.3,
    imageUrl: "food-11.jfif",
    tags: ["Cake"],
  },
  {
    id: "12",
    name: "Stawberry Cake",
    price: 400,
    cookTime: "40-50",
    favorite: false,
    origins: ["italy", "us"],
    stars: 4.0,
    imageUrl: "food-12.jfif",
    tags: ["Cake"],
  },
  {
    id: "13",
    name: "Red Velvet Cake",
    price: 350,
    cookTime: "30-35",
    favorite: true,
    origins: ["italy"],
    stars: 5,
    imageUrl: "food-13.jfif",
    tags: ["Cake"],
  },
  {
    id: "14",
    name: "Chocolate Cake",
    price: 300,
    cookTime: "35-40",
    favorite: true,
    origins: ["india"],
    stars: 4.8,
    imageUrl: "food-14.jfif",
    tags: ["Cake"],
  },
  {
    id: "15",
    name: "Stawberry flavour Cake",
    price: 9,
    cookTime: "25-30",
    favorite: false,
    origins: ["india"],
    stars: 4.2,
    imageUrl: "food-15.jfif",
    tags: ["Cake"],
  },
  {
    id: "16",
    name: "Vanilla Cupcake",
    price: 10,
    cookTime: "5-10",
    favorite: false,
    origins: ["india", "germany", "us"],
    stars: 4.5,
    imageUrl: "food-16.jfif",
    tags: ["Cupcake"],
  },
  {
    id: "17",
    name: "Hot Pink Cupcake",
    price: 20,
    cookTime: "5-10",
    favorite: true,
    origins: ["india", "germany", "us"],
    stars: 4.5,
    imageUrl: "food-17.jfif",
    tags: ["Cupcake"],
  },
  {
    id: "18",
    name: "Chocolate Cupcake",
    price: 10,
    cookTime: "5-10",
    favorite: false,
    origins: ["india"],
    stars: 4.3,
    imageUrl: "food-18.jpg",
    tags: ["Cupcake"],
  },
  {
    id: "19",
    name: "Red Bull",
    price: 80,
    cookTime: "0",
    favorite: true,
    origins: ["india"],
    stars: 4.9,
    imageUrl: "food-19.png",
    tags: ["Drinks"],
  },
  {
    id: "20",
    name: "Monster Energy",
    price: 100,
    cookTime: "0",
    favorite: false,
    origins: ["india", "London"],
    stars: 4.7,
    imageUrl: "food-20.png",
    tags: ["Drinks"],
  },
  {
    id: "21",
    name: "Coco Cola",
    price: 30,
    cookTime: "0",
    favorite: false,
    origins: ["india"],
    stars: 4.3,
    imageUrl: "food-21.png",
    tags: ["Drinks"],
  },
];

export const sample_tags = [
  { name: "All", count: 21 },
  { name: "Breakfast", count: 2 },
  { name: "Chicken", count: 1 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 7 },
  { name: "SlowFood", count: 1 },
  { name: "HamBurger", count: 1 },
  { name: "Fry", count: 1 },
  { name: "Curry", count: 2 },
  { name: "Cake", count: 5 },
  { name: "Cupcake", count: 3 },
  { name: "Drinks", count: 3 },
];

export const sample_users = [
  {
    id: 1,
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: false,
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: true,
  },
];
